# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robert/Desktop/neural-network

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robert/Desktop/neural-network

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robert/Desktop/neural-network/CMakeFiles /home/robert/Desktop/neural-network/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robert/Desktop/neural-network/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NeuralNetwork

# Build rule for target.
NeuralNetwork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NeuralNetwork
.PHONY : NeuralNetwork

# fast build rule for target.
NeuralNetwork/fast:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/build
.PHONY : NeuralNetwork/fast

src/activation.o: src/activation.cpp.o

.PHONY : src/activation.o

# target to build an object file
src/activation.cpp.o:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/activation.cpp.o
.PHONY : src/activation.cpp.o

src/activation.i: src/activation.cpp.i

.PHONY : src/activation.i

# target to preprocess a source file
src/activation.cpp.i:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/activation.cpp.i
.PHONY : src/activation.cpp.i

src/activation.s: src/activation.cpp.s

.PHONY : src/activation.s

# target to generate assembly for a file
src/activation.cpp.s:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/activation.cpp.s
.PHONY : src/activation.cpp.s

src/dataset.o: src/dataset.cpp.o

.PHONY : src/dataset.o

# target to build an object file
src/dataset.cpp.o:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/dataset.cpp.o
.PHONY : src/dataset.cpp.o

src/dataset.i: src/dataset.cpp.i

.PHONY : src/dataset.i

# target to preprocess a source file
src/dataset.cpp.i:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/dataset.cpp.i
.PHONY : src/dataset.cpp.i

src/dataset.s: src/dataset.cpp.s

.PHONY : src/dataset.s

# target to generate assembly for a file
src/dataset.cpp.s:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/dataset.cpp.s
.PHONY : src/dataset.cpp.s

src/encoder.o: src/encoder.cpp.o

.PHONY : src/encoder.o

# target to build an object file
src/encoder.cpp.o:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/encoder.cpp.o
.PHONY : src/encoder.cpp.o

src/encoder.i: src/encoder.cpp.i

.PHONY : src/encoder.i

# target to preprocess a source file
src/encoder.cpp.i:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/encoder.cpp.i
.PHONY : src/encoder.cpp.i

src/encoder.s: src/encoder.cpp.s

.PHONY : src/encoder.s

# target to generate assembly for a file
src/encoder.cpp.s:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/encoder.cpp.s
.PHONY : src/encoder.cpp.s

src/loader.o: src/loader.cpp.o

.PHONY : src/loader.o

# target to build an object file
src/loader.cpp.o:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/loader.cpp.o
.PHONY : src/loader.cpp.o

src/loader.i: src/loader.cpp.i

.PHONY : src/loader.i

# target to preprocess a source file
src/loader.cpp.i:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/loader.cpp.i
.PHONY : src/loader.cpp.i

src/loader.s: src/loader.cpp.s

.PHONY : src/loader.s

# target to generate assembly for a file
src/loader.cpp.s:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/loader.cpp.s
.PHONY : src/loader.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/neural_net.o: src/neural_net.cpp.o

.PHONY : src/neural_net.o

# target to build an object file
src/neural_net.cpp.o:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/neural_net.cpp.o
.PHONY : src/neural_net.cpp.o

src/neural_net.i: src/neural_net.cpp.i

.PHONY : src/neural_net.i

# target to preprocess a source file
src/neural_net.cpp.i:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/neural_net.cpp.i
.PHONY : src/neural_net.cpp.i

src/neural_net.s: src/neural_net.cpp.s

.PHONY : src/neural_net.s

# target to generate assembly for a file
src/neural_net.cpp.s:
	$(MAKE) -f CMakeFiles/NeuralNetwork.dir/build.make CMakeFiles/NeuralNetwork.dir/src/neural_net.cpp.s
.PHONY : src/neural_net.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... NeuralNetwork"
	@echo "... edit_cache"
	@echo "... src/activation.o"
	@echo "... src/activation.i"
	@echo "... src/activation.s"
	@echo "... src/dataset.o"
	@echo "... src/dataset.i"
	@echo "... src/dataset.s"
	@echo "... src/encoder.o"
	@echo "... src/encoder.i"
	@echo "... src/encoder.s"
	@echo "... src/loader.o"
	@echo "... src/loader.i"
	@echo "... src/loader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/neural_net.o"
	@echo "... src/neural_net.i"
	@echo "... src/neural_net.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

